import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack/server";
import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import { Button2 } from "@/components/ui/8bit/button";
  import { ThemeProvider } from "@/components/theme-provider"
import { Navbar } from "@/components/navbar";
  
  interface Item {
    title: string;
    href: string;
  }
  
  const items : Item[] = [
    {title:"Home", href:"/"},
    {title:"Add-Product",href:"/add-product"},
    {title:"Products",href:"/products"}
  ]
  
  
  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });
  
  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Tech Inventory",
    // description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>)
   {
    return (
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
        ><StackProvider app={stackServerApp}><StackTheme>
    <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >

          <div className="min-h-screen w-full relative">
  <div
    className="absolute inset-0 z-0  bg-[radial-gradient(125%_125%_at_50%_10%,_#ffffff_40%,_#7c3aed_100%)]
    dark:bg-[radial-gradient(125%_125%_at_50%_100%,_#000000_40%,_#010133_100%)]"
  />
  <div className="relative z-10">
  <Navbar/>
    {children}
  </div>
</div>
</ThemeProvider>
</StackTheme></StackProvider></body>
</html>
);
}
  